"""
Evaluation of Python Code Generation with CodeGen 350M mono Using the ReCode Approach.

Companion to Chapter 7 of "Domain Specific LLMs in Action" by Guglielmo Iozzia,
Manning Publications, 2024.

Evaluates the quality of Python code generated by the CodeGen 350M mono model
using the ReCode approach. The evaluation dataset is the preprocessed HumanEval
dataset from the ReCode GitHub repository. Only Python code generation can be
evaluated with this script. GPU acceleration is required.

Setup instructions (run once before executing this script):
    git clone https://github.com/openai/human-eval && cd human-eval && pip install . && cd ..
    mkdir -p datasets/nominal/
    wget -P datasets/nominal/ https://raw.githubusercontent.com/amazon-science/recode/refs/heads/main/datasets/nominal/HumanEval.jsonl
    mkdir -p output_dir/output
"""

import ast
import contextlib
import faulthandler
import glob
import gzip
import io
import itertools
import json
import multiprocessing
import os
import platform
import signal
import sys
import tempfile
from collections import Counter, defaultdict
from collections.abc import Callable, Iterable
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Dict, List, Optional, Union

# Ensure root workspace is on pythonpath
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import fire
import numpy as np
import torch
import tqdm
from human_eval.data import HUMAN_EVAL, read_problems, stream_jsonl, write_jsonl
from tqdm import tqdm as tqdm_progress
from transformers import AutoModelForCausalLM, AutoTokenizer, GenerationConfig

from common.ui import (
    STYLE_PRIMARY,
    STYLE_SUCCESS,
    STYLE_TEXT,
    STYLE_WARNING,
    console,
    create_table,
    pause,
    render_banner,
    render_card,
    render_device_info,
    render_step,
    render_takeaways,
    status_spinner,
)

# Model and file path constants
MODEL_ID = "Salesforce/codegen-350M-mono"
PROBLEMS_FILE_PATH = "datasets/nominal/HumanEval.jsonl"
OUTPUT_DIR = "output_dir"
FPATH_FORMAT = os.path.join(OUTPUT_DIR, "output", "taskid-{task_idx}-gen{completion_idx}.json")
DEFAULT_SAMPLE_DIR = "/content/output_dir/output/"
DEFAULT_PROBLEM_FILE = "/content/datasets/nominal/HumanEval.jsonl"
TEMP_SAMPLES_FILE = "/content/output_dir/temp_samples.jsonl"

# Generation hyperparameters
PAD_TOKEN_ID = 50256
MAX_LENGTH = 1000
NUM_SAMPLES = 1
BATCH_SIZE = 1
DEFAULT_TIMEOUT = 3.0
DEFAULT_N_WORKERS = 2
DEFAULT_K_VALUES = "1,10,100"
CODE_GENERATION_LANGUAGE = "python"


# ---- Data loading utilities ----


def read_problems_local(eval_file: str) -> dict[str, dict]:
    """Load problems from a JSONL file, keyed by task_id."""
    return {str(task["task_id"]): task for task in stream_jsonl_local(eval_file)}


def stream_jsonl_local(filename: str):
    """Yield non-empty lines from a JSONL file as parsed dicts."""
    with open(filename) as fp:
        for line in fp:
            if any(not x.isspace() for x in line):
                yield json.loads(line)


def count_files_present_nonempty(list_fname: list[str]):
    """Return (count_of_nonempty_existing_files, total_expected) for a list of paths."""
    count = 0
    for fname in list_fname:
        if os.path.isfile(fname):
            with open(fname, encoding="utf8") as f:
                s = f.read()
            if s != "":
                count += 1
    return count, len(list_fname)


# ---- Token position utilities ----


def get_token_position_by_string(
    target_str: str,
    outputs,
    tokenizer,
    skip_special_tokens: bool,
) -> int:
    """Find the token position corresponding to a target decoded string."""
    for position in range(1, len(outputs) + 1):
        gen_str = tokenizer.decode(
            outputs[:position],
            skip_special_tokens=skip_special_tokens,
            clean_up_tokenization_spaces=False,
        )
        if gen_str.rstrip() == target_str.rstrip():
            return position  # not including outputs[position]
        if gen_str.startswith(target_str) and target_str != "":
            return position
    if target_str.rstrip() == "":
        return 0
    raise RuntimeError("Cannot match prefix returned by AST.")


# ---- AST-based code validation ----


def is_valid_python(code: str):
    """Parse code with the ast module; return parsed AST or False on failure."""
    try:
        try:
            parsed_code = ast.parse(code)
        except SyntaxError:
            return False
    except Exception:
        return False
    return parsed_code


def get_function_from_ast(parsed_code, code: str, option: str = "func_ast_last") -> str:
    """Extract the full source of a function from an AST-parsed code block."""
    assert option in [
        "func_ast_first",
        "func_ast_last",
    ], f"Invalid post process option {option}"
    for i in range(len(parsed_code.body)):
        idx = -i - 1 if option == "func_ast_last" else i
        if type(parsed_code.body[idx]) == ast.FunctionDef:
            break
        idx = None
    assert idx is not None, "No function found"
    function_segment = ast.get_source_segment(code, parsed_code.body[idx])
    position = code.find(function_segment)
    function_segment_plus_previous = code[: position + len(function_segment)]
    return function_segment_plus_previous


# ---- Code generation filtering ----


def filter_valid_code(
    true_str_input: str,
    execution_prompt,
    inputs,
    sequences,
    initial_context_length: int,
    tokenizer,
    task_id=None,
    has_special_tokens: bool = False,
    post_process: str = "greedy",
    replace_unk: bool = False,
    skip_special_tokens: bool = True,
    mean_logp=None,
    use_language_tag: int = 0,
):
    """
    Decode generated sequences and filter for valid Python code.
    """
    samples = []
    decoded_context_string = tokenizer.batch_decode(
        inputs[:, use_language_tag:initial_context_length],
        skip_special_tokens=skip_special_tokens,
        clean_up_tokenization_spaces=False,
    )[0]
    decoded_original_prompt = tokenizer.batch_decode(
        inputs[:, use_language_tag:],
        skip_special_tokens=skip_special_tokens,
        clean_up_tokenization_spaces=False,
    )[0]
    processed_prompt = decoded_context_string
    processed_execution_prompt = processed_prompt

    output_lists = sequences[:, initial_context_length:]
    for sample_id, outputs in enumerate(output_lists):
        is_valid = False
        for position in range(len(outputs), 0, -1):
            gen_up_to_pos_toks = outputs[:position]
            gen_up_to_pos_str = tokenizer.decode(
                gen_up_to_pos_toks,
                skip_special_tokens=skip_special_tokens,
                clean_up_tokenization_spaces=False,
            )
            origin_pred = gen_up_to_pos_str
            code = processed_execution_prompt + gen_up_to_pos_str
            parsed_code = is_valid_python(code)
            if parsed_code:
                is_valid = True
                if post_process != "greedy":
                    try:
                        function_segment_plus_previous = get_function_from_ast(
                            parsed_code,
                            code,
                            option=post_process,
                        )
                        generated_part = function_segment_plus_previous[len(processed_execution_prompt) :]
                    except Exception:
                        generated_part = gen_up_to_pos_str
                elif post_process == "greedy":
                    generated_part = gen_up_to_pos_str
                else:
                    assert False, f"post processing method {post_process} not supported"

                if task_id is None:
                    return generated_part
                if mean_logp is None:
                    score = None
                else:
                    if post_process != "greedy":
                        position = get_token_position_by_string(
                            generated_part,
                            outputs,
                            tokenizer,
                            skip_special_tokens,
                        )
                    if position == 0:
                        score = -1e8
                    else:
                        score = mean_logp[sample_id][position - 1]

                samples.append(
                    dict(
                        task_id=task_id,
                        completion=(processed_prompt + generated_part)[len(decoded_original_prompt) :],
                        ori_pred=(processed_prompt + origin_pred)[len(decoded_original_prompt) :],
                        input=true_str_input,
                        mean_logp=score,
                    )
                )
                break
        if not is_valid:
            predictions = tokenizer.decode(
                outputs,
                skip_special_tokens=skip_special_tokens,
                clean_up_tokenization_spaces=False,
            )
            origin_pred = predictions
            if task_id is None:
                return predictions
            samples.append(
                dict(
                    task_id=task_id,
                    completion=(processed_prompt + predictions)[len(decoded_original_prompt) :],
                    ori_pred=(processed_prompt + origin_pred)[len(decoded_original_prompt) :],
                    input=true_str_input,
                    mean_logp=-1e8,
                )
            )

    return samples


# ---- HumanEval correctness evaluation ----


def custom_check_correctness(
    problem: dict,
    completion: str,
    timeout: float,
    completion_id: int | None = None,
) -> dict:
    """
    Evaluate functional correctness of a completion by running its test suite.
    """

    def unsafe_execute():
        with create_tempdir():
            import os
            import shutil

            rmtree = shutil.rmtree
            rmdir = os.rmdir
            chdir = os.chdir

            reliability_guard()

            check_program = (
                problem["prompt"] + completion + "\n" + problem["test"] + "\n" + f"check({problem['entry_point']})"
            )

            try:
                exec_globals = {}
                with swallow_io():
                    with time_limit(timeout):
                        exec(check_program, exec_globals)
                        result.append("passed")
            except TimeoutException:
                result.append("timed out")
            except BaseException as e:
                result.append(f"failed: {e}")

            shutil.rmtree = rmtree
            os.rmdir = rmdir
            os.chdir = chdir

    manager = multiprocessing.Manager()
    result = manager.list()

    p = multiprocessing.Process(target=unsafe_execute)
    p.start()
    p.join(timeout=timeout + 1)
    if p.is_alive():
        p.kill()

    if not result:
        result.append("timed out")

    return dict(
        task_id=problem["task_id"],
        passed=result[0] == "passed",
        result=result[0],
        completion_id=completion_id,
    )


@contextlib.contextmanager
def time_limit(seconds: float):
    """Context manager that raises TimeoutException after *seconds*."""

    def signal_handler(signum, frame):
        raise TimeoutException("Timed out!")

    signal.setitimer(signal.ITIMER_REAL, seconds)
    signal.signal(signal.SIGALRM, signal_handler)
    try:
        yield
    finally:
        signal.setitimer(signal.ITIMER_REAL, 0)


@contextlib.contextmanager
def swallow_io():
    """Context manager that suppresses all stdout/stderr/stdin."""
    stream = WriteOnlyStringIO()
    with contextlib.redirect_stdout(stream):
        with contextlib.redirect_stderr(stream):
            with redirect_stdin(stream):
                yield


@contextlib.contextmanager
def create_tempdir():
    """Context manager that creates and cds into a temporary directory."""
    with tempfile.TemporaryDirectory() as dirname:
        with chdir(dirname):
            yield dirname


class TimeoutException(Exception):
    pass


class WriteOnlyStringIO(io.StringIO):
    def read(self, *args, **kwargs):
        raise OSError

    def readline(self, *args, **kwargs):
        raise OSError

    def readlines(self, *args, **kwargs):
        raise OSError

    def readable(self):
        return False


class redirect_stdin(contextlib._RedirectStream):  # type: ignore
    _stream = "stdin"


@contextlib.contextmanager
def chdir(root: str):
    if root == ".":
        yield
        return
    cwd = os.getcwd()
    os.chdir(root)
    try:
        yield
    except BaseException as exc:
        raise exc
    finally:
        os.chdir(cwd)


def reliability_guard(maximum_memory_bytes: int | None = None) -> None:
    if maximum_memory_bytes is not None:
        import resource

        resource.setrlimit(resource.RLIMIT_AS, (maximum_memory_bytes, maximum_memory_bytes))
        resource.setrlimit(resource.RLIMIT_DATA, (maximum_memory_bytes, maximum_memory_bytes))
        if not platform.uname().system == "Darwin":
            resource.setrlimit(resource.RLIMIT_STACK, (maximum_memory_bytes, maximum_memory_bytes))

    faulthandler.disable()

    import builtins

    builtins.exit = None
    builtins.quit = None

    import os

    os.environ["OMP_NUM_THREADS"] = "1"

    os.kill = None
    os.system = None
    os.putenv = None
    os.remove = None
    os.removedirs = None
    os.rmdir = None
    os.fchdir = None
    os.setuid = None
    os.fork = None
    os.forkpty = None
    os.killpg = None
    os.rename = None
    os.renames = None
    os.truncate = None
    os.replace = None
    os.unlink = None
    os.fchmod = None
    os.fchown = None
    os.chmod = None
    os.chown = None
    os.chroot = None
    os.fchdir = None
    os.lchflags = None
    os.lchmod = None
    os.lchown = None
    os.getcwd = None
    os.chdir = None

    import shutil

    shutil.rmtree = None
    shutil.move = None
    shutil.chown = None

    import subprocess

    subprocess.Popen = None  # type: ignore

    __builtins__["help"] = None

    sys.modules["ipdb"] = None
    sys.modules["joblib"] = None
    sys.modules["resource"] = None
    sys.modules["psutil"] = None
    sys.modules["tkinter"] = None


# ---- pass@k estimation ----


def estimate_pass_at_k(
    num_samples: int | list[int] | np.ndarray,
    num_correct: list[int] | np.ndarray,
    k: int,
) -> np.ndarray:
    """Estimate pass@k of each problem and return them in an array."""

    def estimator(n: int, c: int, k: int) -> float:
        if n - c < k:
            return 1.0
        return 1.0 - np.prod(1.0 - k / np.arange(n - c + 1, n + 1))

    if isinstance(num_samples, int):
        num_samples_it = itertools.repeat(num_samples, len(num_correct))
    else:
        assert len(num_samples) == len(num_correct)
        num_samples_it = iter(num_samples)

    return np.array([estimator(int(n), int(c), k) for n, c in zip(num_samples_it, num_correct)])


def custom_evaluate_functional_correctness(
    sample_file: str,
    k: list[int] = [1, 10, 100],
    n_workers: int = 4,
    timeout: float = 3.0,
    problem_file: str = HUMAN_EVAL,
) -> dict:
    """
    Evaluate functional correctness of generated samples and write results
    to f"{sample_file}_results.jsonl".
    """
    problems = read_problems(problem_file)

    with ThreadPoolExecutor(max_workers=n_workers) as executor:
        futures = []
        completion_id = Counter()
        n_samples = 0
        results = defaultdict(list)

        console.print("[cyan]Submitting test suites for evaluation...[/cyan]")
        for sample in tqdm.tqdm(stream_jsonl(sample_file)):
            task_id = sample["task_id"]
            completion = sample["completion"]
            args = (problems[task_id], completion, timeout, completion_id[task_id])
            future = executor.submit(custom_check_correctness, *args)
            futures.append(future)
            completion_id[task_id] += 1
            n_samples += 1

        assert len(completion_id) == len(problems), "Some problems are not attempted."

        for future in tqdm.tqdm(as_completed(futures), total=len(futures), desc="Executing unit tests"):
            result = future.result()
            results[result["task_id"]].append((result["completion_id"], result))

    total, correct = [], []
    for result in results.values():
        result.sort()
        passed = [r[1]["passed"] for r in result]
        total.append(len(passed))
        correct.append(sum(passed))
    total = np.array(total)
    correct = np.array(correct)

    pass_at_k = {
        f"pass@{k_val}": estimate_pass_at_k(total, correct, k_val).mean() for k_val in k if (total >= k_val).all()
    }

    def combine_results():
        for sample in stream_jsonl(sample_file):
            task_id = sample["task_id"]
            result = results[task_id].pop(0)
            sample["result"] = result[1]["result"]
            sample["passed"] = result[1]["passed"]
            yield sample

    out_file = sample_file + "_results.jsonl"
    write_jsonl(out_file, combine_results())
    console.print(f"[bold green]✔[/bold green] Results written to [yellow]{out_file}[/yellow]")
    return pass_at_k


# ---- Code generation pipeline ----


def load_model_and_tokenizer(model_id: str, device: str):
    """Load the causal LM and its tokenizer from the HF Hub onto *device*."""
    with console.status(f"[bold green]Loading {model_id} onto {device}..."):
        tokenizer = AutoTokenizer.from_pretrained(model_id)
        model = AutoModelForCausalLM.from_pretrained(model_id).to(device)
        model.eval()
    console.print("[bold green]✔[/bold green] CodeGen model loaded.")
    return model, tokenizer


def build_generation_config() -> GenerationConfig:
    """Return the GenerationConfig used during code generation."""
    return GenerationConfig(
        pad_token_id=PAD_TOKEN_ID,
        truncation=True,
        max_length=MAX_LENGTH,
        max_context_length=MAX_LENGTH,
        use_cache=True,
        return_dict_in_generate=True,
        output_scores=True,
    )


def generate_code_samples(
    model,
    tokenizer,
    problems: dict,
    device: str,
    num_samples: int = NUM_SAMPLES,
    batch_size: int = BATCH_SIZE,
    override_previous_results: bool = False,
) -> None:
    """Iterate over HumanEval prompts and write generated code samples to disk."""
    os.makedirs(os.path.join(OUTPUT_DIR, "output"), exist_ok=True)
    generation_config = build_generation_config()
    execution_prompt = None

    for enum_idx, task_id in enumerate(tqdm_progress(problems, desc="Generating HumanEval completions")):
        task_idx = task_id.split("/")[1]
        if not override_previous_results:
            fnames = [FPATH_FORMAT.format(task_idx=task_idx, completion_idx=_idx) for _idx in range(num_samples)]
            count, all_count = count_files_present_nonempty(fnames)
            if count == all_count:
                continue

        prompt = problems[task_id]["prompt"]
        completion_idx = -1
        for i in range(0, num_samples, batch_size):
            inputs = tokenizer(prompt, return_tensors="pt").to(device)
            input_ids = inputs.input_ids
            output_dict = model.generate(input_ids, generation_config=generation_config)

            sequences = output_dict.sequences
            initial_context_length = len(sequences[0]) - len(output_dict.scores)

            predictions_post_eos = filter_valid_code(
                true_str_input=prompt,
                execution_prompt=execution_prompt,
                inputs=input_ids,
                sequences=sequences,
                initial_context_length=initial_context_length,
                tokenizer=tokenizer,
                task_id=task_id,
                post_process="func_ast_first",
                skip_special_tokens=True,
                mean_logp=None,
            )

            for prediction in predictions_post_eos:
                completion_idx += 1
                fpath = FPATH_FORMAT.format(task_idx=task_idx, completion_idx=completion_idx)
                prediction["language"] = CODE_GENERATION_LANGUAGE
                with open(fpath, "w", encoding="utf8") as _f:
                    json.dump(prediction, _f)


# ---- Entry point (fire-compatible) ----


def entry_point(
    sample_dir: str = DEFAULT_SAMPLE_DIR,
    k: str = DEFAULT_K_VALUES,
    n_workers: int = DEFAULT_N_WORKERS,
    timeout: float = DEFAULT_TIMEOUT,
    problem_file: str = DEFAULT_PROBLEM_FILE,
) -> None:
    """Evaluate functional correctness of generated samples."""
    k_list = list(map(int, k.split(",")))

    sample_files = glob.glob(os.path.join(sample_dir, "*.json"))
    samples = []
    for sample_file in sample_files:
        with open(sample_file, encoding="utf8") as f:
            try:
                samples.append(json.load(f))
            except json.JSONDecodeError:
                continue

    with open(TEMP_SAMPLES_FILE, "w", encoding="utf8") as f:
        for sample in samples:
            json.dump(sample, f)
            f.write("\n")

    results = custom_evaluate_functional_correctness(TEMP_SAMPLES_FILE, k_list, n_workers, timeout, problem_file)

    columns = [("Metric", STYLE_PRIMARY, "left"), ("pass@k Score", STYLE_SUCCESS, "right")]
    rows = [(metric, f"{score * 100:.2f}%") for metric, score in results.items()]
    console.print(create_table("HumanEval pass@k Evaluation Metrics", columns, rows))
    pause()

    if os.path.exists(TEMP_SAMPLES_FILE):
        os.remove(TEMP_SAMPLES_FILE)


def main() -> None:
    """Orchestrate model loading, code generation, and correctness evaluation."""
    render_banner(
        title="ReCode Evaluation of CodeGen 350M on HumanEval",
        subtitle="Chapter 7: Domain-Specific Small Language Models",
        metadata={
            "Model": MODEL_ID,
            "Problems File": PROBLEMS_FILE_PATH,
            "Target Language": CODE_GENERATION_LANGUAGE.capitalize(),
        },
        icon="🚀",
    )

    device = "cuda" if torch.cuda.is_available() else "cpu"
    render_step(1, "Loading Model and HumanEval Problem Set", icon="📋")
    model, tokenizer = load_model_and_tokenizer(MODEL_ID, device)
    render_device_info(device, model=model)
    problems = read_problems_local(PROBLEMS_FILE_PATH)
    render_card(
        "Problems Loaded",
        f"Successfully loaded [text.highlight]{len(problems)}[/text.highlight] HumanEval coding challenges.",
        icon="✔",
    )

    render_step(2, "Generating Code Samples & Performing AST Filtering", icon="⚙️")
    generate_code_samples(model, tokenizer, problems, device)

    render_step(3, "Evaluating Functional Correctness via Fire CLI", icon="📊")
    fire.Fire(entry_point)

    render_takeaways(
        points=(
            (
                "ReCode AST Parsing",
                "Validates generated code using Python's ast.parse to extract complete function definitions and discard syntax-broken completions.",
            ),
            (
                "pass@k Estimation",
                "Evaluates the probability that at least one of k generated candidates passes all unit test assertions without requiring combinatorial explosions.",
            ),
            (
                "Sandboxed Test Execution",
                "Runs student/model code in isolated sub-processes with strict CPU and memory limits to prevent infinite loops or security escapes.",
            ),
        ),
    )


if __name__ == "__main__":
    main()
